"""initial schema

Revision ID: 89b3589cbecd
Revises: 
Create Date: 2026-09-05 10:39:37.059143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b3589cbecd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- Manual additions beyond autogenerate ---
    # pg_trgm powers the trigram GIN index on employees.full_name (search box).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('salary_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('basic', 'allowance', 'deduction', 'gross', 'contribution', 'net', name='salaryrulecategory'), nullable=False),
    sa.Column('computation_method', sa.Enum('fixed', 'percentage', 'formula', name='computationmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('percentage_base_code', sa.String(length=30), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('default_sequence', sa.SmallInteger(), server_default='10', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(computation_method = 'fixed' AND amount IS NOT NULL AND percentage IS NULL AND formula IS NULL) OR (computation_method = 'percentage' AND percentage IS NOT NULL AND amount IS NULL AND formula IS NULL) OR (computation_method = 'formula' AND formula IS NOT NULL AND amount IS NULL AND percentage IS NULL)", name=op.f('ck_salary_rules_ck_salary_rules_method_consistency')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_rules')),
    sa.UniqueConstraint('code', name=op.f('uq_salary_rules_code'))
    )
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_department_id', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_departments_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], name=op.f('fk_departments_parent_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', 'company_id', name='uq_departments_name_company')
    )
    op.create_index(op.f('ix_departments_company_id'), 'departments', ['company_id'], unique=False)
    op.create_index(op.f('ix_departments_parent_department_id'), 'departments', ['parent_department_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('salary_structures',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_salary_structures_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_structures')),
    sa.UniqueConstraint('code', name=op.f('uq_salary_structures_code'))
    )
    op.create_index(op.f('ix_salary_structures_company_id'), 'salary_structures', ['company_id'], unique=False)
    op.create_table('time_off_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.Enum('days', 'hours', name='time_off_unit'), nullable=False),
    sa.Column('requires_allocation', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('requires_approval', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('affects_payroll', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_time_off_types_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_off_types')),
    sa.UniqueConstraint('name', 'company_id', name='uq_time_off_types_name_company')
    )
    op.create_index(op.f('ix_time_off_types_company_id'), 'time_off_types', ['company_id'], unique=False)
    op.create_table('working_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('schedule_type', sa.Enum('full_time', 'part_time', 'custom', name='schedule_type'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_working_schedules_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_working_schedules'))
    )
    op.create_index(op.f('ix_working_schedules_company_id'), 'working_schedules', ['company_id'], unique=False)
    op.create_table('job_positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_job_positions_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_positions')),
    sa.UniqueConstraint('title', 'department_id', name='uq_job_positions_title_department')
    )
    op.create_index(op.f('ix_job_positions_department_id'), 'job_positions', ['department_id'], unique=False)
    op.create_table('salary_structure_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('salary_structure_id', sa.BigInteger(), nullable=False),
    sa.Column('salary_rule_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['salary_rule_id'], ['salary_rules.id'], name=op.f('fk_salary_structure_rules_salary_rule_id_salary_rules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name=op.f('fk_salary_structure_rules_salary_structure_id_salary_structures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_structure_rules')),
    sa.UniqueConstraint('salary_structure_id', 'salary_rule_id', name='uq_salary_structure_rules_structure_rule')
    )
    op.create_index('ix_salary_structure_rules_structure_sequence', 'salary_structure_rules', ['salary_structure_id', 'sequence'], unique=False)
    op.create_table('working_schedule_lines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('working_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.SmallInteger(), server_default='0', nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name=op.f('ck_working_schedule_lines_ck_working_schedule_lines_day_of_week_range')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_working_schedule_lines_ck_working_schedule_lines_end_after_start')),
    sa.ForeignKeyConstraint(['working_schedule_id'], ['working_schedules.id'], name=op.f('fk_working_schedule_lines_working_schedule_id_working_schedules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_working_schedule_lines'))
    )
    op.create_index('ix_working_schedule_lines_schedule_id', 'working_schedule_lines', ['working_schedule_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('work_email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('job_position_id', sa.BigInteger(), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('working_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_type', sa.Enum('full_time', 'part_time', 'contract', 'intern', name='employeetype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'terminated', name='employeestatus'), server_default='active', nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('work_location', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employees_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employees_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], name=op.f('fk_employees_job_position_id_job_positions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name=op.f('fk_employees_manager_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['working_schedule_id'], ['working_schedules.id'], name=op.f('fk_employees_working_schedule_id_working_schedules'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('work_email', name=op.f('uq_employees_work_email'))
    )
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index('ix_employees_department_id', 'employees', ['department_id'], unique=False)
    op.create_index('ix_employees_employee_type', 'employees', ['employee_type'], unique=False)
    op.create_index('ix_employees_full_name_trgm', 'employees', ['full_name'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index('ix_employees_job_position_id', 'employees', ['job_position_id'], unique=False)
    op.create_index('ix_employees_manager_id', 'employees', ['manager_id'], unique=False)
    op.create_index('ix_employees_status', 'employees', ['status'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_number', sa.String(length=30), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('job_position_id', sa.BigInteger(), nullable=False),
    sa.Column('working_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('salary_structure_id', sa.BigInteger(), nullable=False),
    sa.Column('wage_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'running', 'expired', 'cancelled', name='contractstatus'), server_default='draft', nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_contracts_ck_contracts_end_after_start')),
    sa.CheckConstraint('wage_monthly >= 0', name=op.f('ck_contracts_ck_contracts_wage_non_negative')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_contracts_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_contracts_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], name=op.f('fk_contracts_job_position_id_job_positions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name=op.f('fk_contracts_salary_structure_id_salary_structures'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['working_schedule_id'], ['working_schedules.id'], name=op.f('fk_contracts_working_schedule_id_working_schedules'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts')),
    sa.UniqueConstraint('contract_number', name=op.f('uq_contracts_contract_number'))
    )
    op.create_index(op.f('ix_contracts_employee_id'), 'contracts', ['employee_id'], unique=False)
    op.create_index('uq_contracts_one_running_per_employee', 'contracts', ['employee_id'], unique=True, postgresql_where="status = 'running'")
    op.create_table('employee_bank_details',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('account_holder_name', sa.String(length=150), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('account_number', sa.String(length=34), nullable=True),
    sa.Column('ifsc_or_swift', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_bank_details_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_bank_details')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_employee_bank_details_employee_id'))
    )
    op.create_table('time_off_allocations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('time_off_type_id', sa.BigInteger(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'to_approve', 'approved', 'refused', name='allocationstatus'), server_default='draft', nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=True),
    sa.Column('version_id', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocated_amount > 0', name=op.f('ck_time_off_allocations_ck_time_off_allocations_amount_positive')),
    sa.ForeignKeyConstraint(['approver_id'], ['employees.id'], name=op.f('fk_time_off_allocations_approver_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_time_off_allocations_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], name=op.f('fk_time_off_allocations_time_off_type_id_time_off_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_off_allocations'))
    )
    op.create_index('ix_time_off_allocations_emp_type_status', 'time_off_allocations', ['employee_id', 'time_off_type_id', 'status'], unique=False)
    op.create_table('time_off_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('time_off_type_id', sa.BigInteger(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('duration', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'to_approve', 'approved', 'refused', 'cancelled', name='timeoffrequeststatus'), server_default='to_approve', nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('date_to >= date_from', name=op.f('ck_time_off_requests_ck_time_off_requests_date_range')),
    sa.CheckConstraint('duration > 0', name=op.f('ck_time_off_requests_ck_time_off_requests_duration_positive')),
    sa.ForeignKeyConstraint(['approver_id'], ['employees.id'], name=op.f('fk_time_off_requests_approver_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_time_off_requests_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], name=op.f('fk_time_off_requests_time_off_type_id_time_off_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_off_requests'))
    )
    op.create_index('ix_time_off_requests_employee_status', 'time_off_requests', ['employee_id', 'status'], unique=False)
    op.create_index('ix_time_off_requests_type', 'time_off_requests', ['time_off_type_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_users_employee_id_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_table('attendances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.Enum('present', 'late', 'absent', 'overtime', 'missing_checkout', name='attendancestatus'), nullable=False),
    sa.Column('is_manual_correction', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('corrected_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_out IS NULL OR check_out > check_in', name=op.f('ck_attendances_ck_attendances_checkout_after_checkin')),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['users.id'], name=op.f('fk_attendances_corrected_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendances_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendances'))
    )
    op.create_index(op.f('ix_attendances_corrected_by_user_id'), 'attendances', ['corrected_by_user_id'], unique=False)
    op.create_index('ix_attendances_employee_checkin', 'attendances', ['employee_id', 'check_in'], unique=False)
    op.create_index('ix_attendances_status', 'attendances', ['status'], unique=False)
    op.create_table('payruns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('salary_structure_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('department_filter_id', sa.BigInteger(), nullable=True),
    sa.Column('employee_type_filter', sa.Enum('full_time', 'part_time', 'contract', 'intern', name='employeetype'), nullable=True),
    sa.Column('status', sa.Enum('draft', 'computed', 'validated', 'paid', 'cancelled', name='payrunstatus'), server_default='draft', nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_payruns_ck_payruns_period_range')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_payruns_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_filter_id'], ['departments.id'], name=op.f('fk_payruns_department_filter_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name=op.f('fk_payruns_salary_structure_id_salary_structures'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payruns'))
    )
    op.create_index(op.f('ix_payruns_department_filter_id'), 'payruns', ['department_filter_id'], unique=False)
    op.create_index('ix_payruns_period', 'payruns', ['period_start', 'period_end'], unique=False)
    op.create_index('ix_payruns_status', 'payruns', ['status'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('payrun_employees',
    sa.Column('payrun_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payrun_employees_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], name=op.f('fk_payrun_employees_payrun_id_payruns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payrun_id', 'employee_id', name=op.f('pk_payrun_employees'))
    )
    op.create_table('payslips',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payrun_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('worked_days', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('draft', 'computed', 'validated', 'paid', 'cancelled', name='payrunstatus'), server_default='draft', nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_payslips_contract_id_contracts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payslips_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], name=op.f('fk_payslips_payrun_id_payruns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslips')),
    sa.UniqueConstraint('payrun_id', 'employee_id', name='uq_payslips_payrun_employee')
    )
    op.create_index(op.f('ix_payslips_contract_id'), 'payslips', ['contract_id'], unique=False)
    op.create_index('ix_payslips_employee_period', 'payslips', ['employee_id', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_payslips_payrun_id', 'payslips', ['payrun_id'], unique=False)
    op.create_table('payslip_lines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payslip_id', sa.BigInteger(), nullable=False),
    sa.Column('salary_rule_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('basic', 'allowance', 'deduction', 'gross', 'contribution', 'net', name='salaryrulecategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], name=op.f('fk_payslip_lines_payslip_id_payslips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salary_rule_id'], ['salary_rules.id'], name=op.f('fk_payslip_lines_salary_rule_id_salary_rules'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslip_lines'))
    )
    op.create_index('ix_payslip_lines_payslip_sequence', 'payslip_lines', ['payslip_id', 'sequence'], unique=False)
    op.create_table('payslip_warnings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payslip_id', sa.BigInteger(), nullable=False),
    sa.Column('warning_type', sa.Enum('missing_bank_details', 'duplicate_payslip', 'missing_contract', 'negative_net', 'overlapping_period', 'other', name='payslipwarningtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], name=op.f('fk_payslip_warnings_payslip_id_payslips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslip_warnings'))
    )
    op.create_index('ix_payslip_warnings_payslip_id', 'payslip_warnings', ['payslip_id'], unique=False)
    # ### end Alembic commands ###

    # --- Manual additions beyond autogenerate ---
    # Live time-off balance view (documented denormalization exception #2:
    # balance is deliberately NOT stored — see README §Denormalization).
    op.execute(
        """
        CREATE OR REPLACE VIEW v_time_off_balances AS
        SELECT
            t.employee_id,
            t.time_off_type_id,
            COALESCE(a.allocated, 0)::NUMERIC(12,2) AS allocated,
            COALESCE(r.taken, 0)::NUMERIC(12,2) AS taken,
            (COALESCE(a.allocated, 0) - COALESCE(r.taken, 0))::NUMERIC(12,2) AS remaining
        FROM (
            SELECT employee_id, time_off_type_id FROM time_off_allocations
            UNION
            SELECT employee_id, time_off_type_id FROM time_off_requests
        ) t
        LEFT JOIN (
            SELECT employee_id, time_off_type_id, SUM(allocated_amount) AS allocated
            FROM time_off_allocations
            WHERE status = 'approved'
              AND (valid_to IS NULL OR valid_to >= CURRENT_DATE)
            GROUP BY employee_id, time_off_type_id
        ) a ON a.employee_id = t.employee_id AND a.time_off_type_id = t.time_off_type_id
        LEFT JOIN (
            SELECT employee_id, time_off_type_id, SUM(duration) AS taken
            FROM time_off_requests
            WHERE status = 'approved'
            GROUP BY employee_id, time_off_type_id
        ) r ON r.employee_id = t.employee_id AND r.time_off_type_id = t.time_off_type_id
        """
    )
    # Derived weekly working hours per schedule (never stored — 3NF, §5).
    op.execute(
        """
        CREATE OR REPLACE VIEW v_working_schedule_hours AS
        SELECT
            working_schedule_id,
            ROUND(
                EXTRACT(EPOCH FROM SUM(
                    end_time - start_time - make_interval(mins => break_minutes)
                )) / 3600.0, 2
            )::NUMERIC(10,2) AS total_weekly_hours
        FROM working_schedule_lines
        GROUP BY working_schedule_id
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # --- Manual additions beyond autogenerate ---
    op.execute("DROP VIEW IF EXISTS v_time_off_balances")
    op.execute("DROP VIEW IF EXISTS v_working_schedule_hours")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payslip_warnings_payslip_id', table_name='payslip_warnings')
    op.drop_table('payslip_warnings')
    op.drop_index('ix_payslip_lines_payslip_sequence', table_name='payslip_lines')
    op.drop_table('payslip_lines')
    op.drop_index('ix_payslips_payrun_id', table_name='payslips')
    op.drop_index('ix_payslips_employee_period', table_name='payslips')
    op.drop_index(op.f('ix_payslips_contract_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_table('payrun_employees')
    op.drop_table('user_roles')
    op.drop_index('ix_payruns_status', table_name='payruns')
    op.drop_index('ix_payruns_period', table_name='payruns')
    op.drop_index(op.f('ix_payruns_department_filter_id'), table_name='payruns')
    op.drop_table('payruns')
    op.drop_index('ix_attendances_status', table_name='attendances')
    op.drop_index('ix_attendances_employee_checkin', table_name='attendances')
    op.drop_index(op.f('ix_attendances_corrected_by_user_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_time_off_requests_type', table_name='time_off_requests')
    op.drop_index('ix_time_off_requests_employee_status', table_name='time_off_requests')
    op.drop_table('time_off_requests')
    op.drop_index('ix_time_off_allocations_emp_type_status', table_name='time_off_allocations')
    op.drop_table('time_off_allocations')
    op.drop_table('employee_bank_details')
    op.drop_index('uq_contracts_one_running_per_employee', table_name='contracts', postgresql_where="status = 'running'")
    op.drop_index(op.f('ix_contracts_employee_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_employees_status', table_name='employees')
    op.drop_index('ix_employees_manager_id', table_name='employees')
    op.drop_index('ix_employees_job_position_id', table_name='employees')
    op.drop_index('ix_employees_full_name_trgm', table_name='employees', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_index('ix_employees_employee_type', table_name='employees')
    op.drop_index('ix_employees_department_id', table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_working_schedule_lines_schedule_id', table_name='working_schedule_lines')
    op.drop_table('working_schedule_lines')
    op.drop_index('ix_salary_structure_rules_structure_sequence', table_name='salary_structure_rules')
    op.drop_table('salary_structure_rules')
    op.drop_index(op.f('ix_job_positions_department_id'), table_name='job_positions')
    op.drop_table('job_positions')
    op.drop_index(op.f('ix_working_schedules_company_id'), table_name='working_schedules')
    op.drop_table('working_schedules')
    op.drop_index(op.f('ix_time_off_types_company_id'), table_name='time_off_types')
    op.drop_table('time_off_types')
    op.drop_index(op.f('ix_salary_structures_company_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_departments_parent_department_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_company_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('salary_rules')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('companies')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
